name: doctor_apps
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.2
  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  provider: ^4.3.3



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true
  assets:
    - images/09-removebg-preview.png
    - images/dental_surgeon.png
    - images/5 Image.jpg
    - images/3d-female-character-with-404-error-message_23-2148938897.jpg
    - 3d-female-character-with-404-error-message_23-2148938897.png
    - images/09.jpg
    - images/Ibu Mengandung.jpg
    - images/cartoon of pregnant woman.jpg
    - images/ibu mengandung 2.jpg
    - images/clip-art-dokter-6.png
    - images/ibu mengandung 2.png
    - images/Doctor_Monochromatic.png
    - images/mata-animasi-png-2.png
    - images/smiling-baby.jpg
    - images/bedah.jpg
    - images/agency-healthcare-clipart-5.png
    - images/Logo Kementrian Kesehatan.png
    - images/Docter 1.jpeg
    - images/dr Citra Farmalita Sp M.jpeg
    - images/dr Ferriyanto Sutiono, Sp.OG.jpeg
    - images/dr Helena Sunarja, Sp.OG.jpeg
    - images/dr Martinus M leman Dtmh Sp A.jpeg
    - images/dr Mervinna Giovanni MioMed, Sp.OG.jpeg
    - images/dr Natalia Stevanie Sp M.jpeg
    - images/dr Patricia Wonodiharyanto Sp A.jpeg
    - images/dr ristania  Sp m.jpeg
    - images/dr Romi Alfianto Mked Sp.OG.jpeg
    - images/dr Vania Catleya Estina Sp A .jpeg

  # To add assets to your application, add an assets section, like this:

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
